apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sourceoftruth
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/admondtamang/dotfiles.git
    targetRevision: HEAD
    path: ops/kubernetes/argocd/apps
  destination:
    server: https://kubernetes.default.svc
    namespace: sourceoftruth
  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
