apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sourceoftruth
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/admondtamang/ops.git
    targetRevision: HEAD
    path: apps
  destination:
    server: https://kubernetes.default.svc
    namespace: sourceoftruth
  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-ingress
  namespace: argocd
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - argo.admondtamang.com.np
      secretName: argo-tls
  rules:
    - host: argo.admondtamang.com.np
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argocd-server
                port:
                  number: 80
