apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - chart: grafana
      repoURL: https://grafana.github.io/helm-charts
      targetRevision: 9.0.0
      helm:
        values: |
          ingress:
            annotations: 
              kubernetes.io/ingress.class: traefik
              cert-manager.io/cluster-issuer: letsencrypt-prod
            enabled: true
            hosts:
              - grafana.admondtamang.com.np
            tls:
              - hosts:
                  - grafana.admondtamang.com.np
                secretName: grafana-tls

  destination:
    namespace: default
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
