apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: uptime-kuma
  namespace: argocd
spec:
  project: default
  sources:
    - chart: uptime-kuma
      repoURL: "https://dirsigler.github.io/uptime-kuma-helm/"
      targetRevision: 2.x.x
      helm:
        values: |
          ingress:
            enabled: true
            annotations:
              cert-manager.io/issuer: "letsencrypt-prod"
            tls:
              - secretName: kuma-tls
                hosts:
                  - kuma.admondtamang.com.np
            hosts:
              - host: kuma.admondtamang.com.np
                paths:
                  - path: /
                    pathType: ImplementationSpecific

  destination:
    namespace: default
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
