apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: uptime-kuma
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  sources:
    - chart: uptime-kuma
      repoURL: "https://dirsigler.github.io/uptime-kuma-helm/"
      targetRevision: 2.x.x
      helm:
        values: |
          ingress:
            enabled: true
            hostname: kuma.admondtamang.com.np

  destination:
    namespace: default
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
