apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plain-kustomize
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/admondtamang/ops.git
    targetRevision: HEAD
    path: kustomize

  destination:
    server: https://kubernetes.default.svc
    namespace: sourceoftruth
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
