apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  project: default
  sources:
    - chart: longhorn
      repoURL: https://charts.longhorn.io/
      targetRevision: v1.8.1 # Replace with the Longhorn version you'd like to install or upgrade to
      helm:
        values: |
          ingress:
            annotations:
              cert-manager.io/cluster-issuer: "letsencrypt-prod"
            enabled: false
            ingressClassName: traefik
            host: sslip.io
            tls: false
            tlsSecret: longhorn.local-tls
            path: /
            pathType: ImplementationSpecific
          preUpgradeChecker:
            jobEnabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
