apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mysql
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  sources:
    - chart: mysql
      path: mysql
      repoURL: "registry-1.docker.io/bitnamicharts"
      targetRevision: 12.3.3
      helm:
        values: |
          networkPolicy:
            enabled: true
            allowExternal: true
          architecture: standalone
          auth:
            rootPassword: "demo"
            createDatabase: true
            database: "demo"
            username: "demo"
            password: "demo"

  destination:
    namespace: default
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
