apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: n8n
  namespace: argocd
spec:
  project: default
  sources:
    - chart: n8n
      repoURL: 8gears.container-registry.com/library
      path: n8n
      targetRevision: 1.0.0
      helm:
        values: |
          ingress:
            enabled: true
            hosts:
              - host: n8n.admondtamang.com.np
                paths: []
            tls:
              - hosts:
                  - n8n.admondtamang.com.np
                secretName: n8n-tls

  destination:
    namespace: argocd
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
