apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: n8n
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - chart: n8n
      repoURL: 8gears.container-registry.com/library
      path: n8n
      targetRevision: 1.0.0
      helm:
        values: |
          ingress:
            annotations: 
              kubernetes.io/ingress.class: traefik
              cert-manager.io/cluster-issuer: letsencrypt-prod
            enabled: true
            hosts:
              - host: n8n.admondtamang.com.np
                paths:
                  - /
            tls:
              - hosts:
                  - n8n.admondtamang.com.np
                secretName: n8n-tls

  destination:
    namespace: default
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
