apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  sources:
    - chart: redis
      repoURL: "registry-1.docker.io/bitnamicharts"
      targetRevision: "17.x.x"
      helm:
        values: |
          architecture: standalone
          auth:
            enabled: true
            password: Password@123
          master:
            service:
              type: ClusterIP
              ports:
                redis: 6379
          replica:
            replicaCount: 0
  destination:
    namespace: default
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
