apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-server-deployment
  namespace: default
  labels:
    app: go-server-deployment
spec:
  selector:
    matchLabels:
      app: go-server-deployment
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: go-server-deployment
    spec:
      containers:
        - name: go-server-deployment
          image: nginx:alpine
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: myjob
  namespace: default
spec:
  selector:
    app: go-server-deployment
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: localapi-ingress
  namespace: argocd
  annotations:
    cert-manager.io/issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - sub.admondtamang.com.np
      secretName: nginx-deployment-tls
  rules:
    - host: sub.admondtamang.com.np
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: myjob
                port:
                  number: 8080
