apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - chart: vault
      repoURL: "https://helm.releases.hashicorp.com"
      targetRevision: 0.30.0
      helm:
        values: |
          injector:
            enabled: false
          ui:
            enabled: true
          server:
            ha:
              enabled: true
              replicas: 1
              raft:
                enabled: true
                setNodeId: true
            dataStorage:
              enabled: true
              size: 10Gi
            resources:
              requests:
                memory: "512Mi"
                cpu: "250m"
              limits:
                memory: "1Gi"
                cpu: "500m"

  destination:
    namespace: vault
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
